package subway.exception;

public enum ExceptionType {
    INVALID_DISTANCE,
    LINE_HAS_STATION, LINE_HAS_NO_SECTION, NON_EXISTENT_SECTION, SECTION_CAN_NOT_BE_SPLITED, NOT_LAST_STOP, NO_SOURCE, STATION_ALREADY_EXIST, STATION_NO_EXIST_IN_LINE, NO_EXISTENT_STATION, NO_EXISTENT_LINE,

}
