package subway.exception;

public enum ExceptionType {
    INVALID_DISTANCE,
    LINE_HAS_STATION,
    LINE_IS_NOT_INITIALIZED,
    NON_EXISTENT_SECTION,
    SECTION_CAN_NOT_BE_SPLITED,
    NOT_LAST_STOP,
    NO_SOURCE,
    STATION_ALREADY_EXIST_IN_LINE,
    STATION_NO_EXIST_IN_LINE,
    NO_EXISTENT_STATION, UN_EXISTED_LINE,
    UN_EXISTED_STATION,
}
