### 노선에 역 등록 API
POST {{local}}/lines/2/stations
Content-Type: application/json

{
  "upStationId": 2,
  "downStationId": 3,
  "distance": 5
}

### 노선에 역 제거 API
DELETE {{local}}/lines/1/stations/1
Content-Type: application/json


### 모든 노선 조회 API
GET {{local}}/lines
Content-Type: application/json


### 노선 조회 API
GET {{local}}/lines/2
Content-Type: application/json

### 경로 조회 API
GET {{local}}/path?srcStationId=3&dstStationId=5
Content-Type: application/json
