INSERT INTO LINE (name)
VALUES ('2호선');
INSERT INTO LINE (name)
VALUES ('3호선');

INSERT INTO STATION (name)
VALUES ('잠실');
INSERT INTO STATION (name)
VALUES ('강남');
INSERT INTO STATION (name)
VALUES ('선릉');
INSERT INTO STATION (name)
VALUES ('삼성');
