POST http://localhost:8080/lines
Content-Type: application/json

{
  "name" : "1호선",
  "color" : "red"
}

###
POST http://localhost:8080/lines
Content-Type: application/json

{
  "name" : "2호선",
  "color" : "blue"
}

###
POST http://localhost:8080/stations
Content-Type: application/json

{
  "name" : "A"
}

###
POST http://localhost:8080/stations
Content-Type: application/json

{
  "name" : "B"
}

###
POST http://localhost:8080/stations
Content-Type: application/json

{
  "name" : "C"
}

###
POST http://localhost:8080/stations
Content-Type: application/json

{
  "name" : "D"
}

###
POST http://localhost:8080/stations
Content-Type: application/json

{
  "name" : "E"
}

###
POST http://localhost:8080/subway/1
Content-Type: application/json

{
  "upBound" : 1,
  "downBound" : 2,
  "distance" : 2
}

###
POST http://localhost:8080/subway/1
Content-Type: application/json

{
  "upBound" : 2,
  "downBound" : 3,
  "distance" : 1
}

###
POST http://localhost:8080/subway/1
Content-Type: application/json

{
  "upBound" : 3,
  "downBound" : 4,
  "distance" : 3
}

###
POST http://localhost:8080/subway/2
Content-Type: application/json

{
  "upBound" : 4,
  "downBound" : 5,
  "distance" : 1
}

###
POST http://localhost:8080/journey
Content-Type: application/json

{
  "departure" : 1,
  "terminal" : 5
}

