DROP TABLE IF EXISTS SECTION;
DROP TABLE IF EXISTS LINE;
DROP TABLE IF EXISTS STATION;

CREATE TABLE STATION
(
    id   BIGINT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
) COMMENT '역';

CREATE TABLE LINE
(
    id        BIGINT AUTO_INCREMENT NOT NULL,
    name      VARCHAR(255) NOT NULL UNIQUE,
    color     VARCHAR(255) NOT NULL UNIQUE,
    extra_fee INT          NOT NULL,
    PRIMARY KEY (id)
) COMMENT '노선';

CREATE TABLE SECTION
(
    id              BIGINT AUTO_INCREMENT NOT NULL,
    line_id         BIGINT,
    up_station_id   BIGINT,
    down_station_id BIGINT,
    distance        INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (line_id) REFERENCES LINE (id) ON DELETE CASCADE,
    FOREIGN KEY (up_station_id) REFERENCES STATION (id) ON DELETE CASCADE,
    FOREIGN KEY (down_station_id) REFERENCES STATION (id) ON DELETE CASCADE
) COMMENT '구간';
