CREATE TABLE IF NOT EXISTS LINE
(
    id BIGINT UNSIGNED NOT NULL auto_increment,
    name VARCHAR(255) NOT NULL UNIQUE,
    color VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
    );

CREATE TABLE IF NOT EXISTS SECTION
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    distance BIGINT UNSIGNED NOT NULL ,
    upstation VARCHAR(20) NOT NULL,
    downstation VARCHAR(20) NOT NULL,
    line_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (line_id) REFERENCES LINE(id) ON DELETE CASCADE
    );
