
###
POST http://localhost:8080/lines
Content-Type: application/json

{
  "name": "2호선",
  "color": "green"
}

### POST /lines/{id}/stationss/init : 첫 두 역(1,2) 삽입
POST http://localhost:8080/lines/1/stationss/init
Content-Type: application/json

{
  "upStationId": 1,
  "downStationId": 2,
  "distance": 10
}

### POST /lines/{id}/stations : 중간 역(3) 삽입
POST http://localhost:8080/lines/1/stations
Content-Type: application/json

{
  "upStationId": 1,
  "downStationId": 3,
  "distance": 4
}

### POST /lines/{id}/stations : 상행종점 역(4) 삽입
POST http://localhost:8080/lines/1/stations
Content-Type: application/json

{
  "upStationId": 4,
  "downStationId": 1,
  "distance": 3
}

### POST /lines/{id}/stations : 하행종점 역(5) 삽입
POST http://localhost:8080/lines/1/stations
Content-Type: application/json

{
  "upStationId": 2,
  "downStationId": 5,
  "distance": 7
}

### DELETE /lines/{id}/stationss/{stationId}
DELETE http://localhost:8080/lines/1/stationss/3

### GET /lines
GET http://localhost:8080/lines

### GET /lines/{id}
GET http://localhost:8080/lines/1

