### 초기 두 역 등록
PATCH http://localhost:8080/lines/4/stations/3?type=init
Content-Type: application/json

{
  "nextStationId": "4",
  "distance": "3"
}

### 상행 종점 등록
PATCH http://localhost:8080/lines/3/stations/3?type=up
Content-Type: application/json

{
  "distance": "1"
}


### 하행 종점 등록
PATCH http://localhost:8080/lines/6/stations/2?type=down
Content-Type: application/json

{
  "distance": "1"
}

### 중간역 등록
PATCH http://localhost:8080/lines/4/stations/5?type=mid
Content-Type: application/json

{
  "distance": "1",
  "prevStationId": "1"
}


### 라인에 등록된 역 정보 삭제
DELETE http://localhost:8080/lines/3/stations/1

### 라인에 해당하는 모든 역 조회
GET http://localhost:8080/lines/4/stations

### 모든 역 조회
GET http://localhost:8080/lines/stations