
###
POST http://localhost:8080/lines
Content-Type: application/json

{
  "name": "2호선",
  "color": "green"
}


### 한 노선에서 첫 등록인 경우 (역이 두개 입력), type: 'init'
POST http://localhost:8080/stations/
Content-Type: application/json

[
  {
    "name": "잠실역",
    "create_type": "INIT",
    "line": "2호선",
    "up_endpoint": true,
    "down_endpoint": false,
    "previous_station": null,
    "previous_distance": null,
    "next_station": "잠실나루역",
    "next_distance": 1
  },
  {
    "name": "잠실나루역",
    "create_type": "INIT",
    "line": "2호선",
    "up_endpoint": false,
    "down_endpoint": true,
    "previous_station": "잠실역",
    "previous_distance": 1,
    "next_station": null,
    "next_distance": null
  }
]
