DROP TABLE LINE_NODE;
DROP TABLE STATION;
DROP TABLE LINE;

CREATE TABLE IF NOT EXISTS STATION
(
    ID   BIGINT       NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LINE_NODE
(
    ID              BIGINT        NOT NULL AUTO_INCREMENT,
    BEFORE_NODE     BIGINT,
    STATION         VARCHAR(255)  NOT NULL,
    NEXT_NODE       BIGINT,
    BEFORE_DISTANCE INT DEFAULT 0 NOT NULL,
    NEXT_DISTANCE   INT DEFAULT 0 NOT NULL,
    LINE_ID         BIGINT        NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BEFORE_NODE) REFERENCES LINE_NODE (ID),
    FOREIGN KEY (NEXT_NODE) REFERENCES LINE_NODE (ID),
    FOREIGN KEY (STATION) REFERENCES STATION (NAME),
    FOREIGN KEY (LINE_ID) REFERENCES LINE (ID)
);

CREATE TABLE IF NOT EXISTS LINE
(
    ID   BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255)          NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);
