DROP TABLE SECTION;
DROP TABLE STATION;
DROP TABLE LINE;

CREATE TABLE IF NOT EXISTS STATION
(
    ID   BIGINT       NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LINE
(
    ID   BIGINT AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255)          NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SECTION
(
    ID             BIGINT        NOT NULL AUTO_INCREMENT,
    BEFORE_STATION BIGINT,
    NEXT_STATION   BIGINT,
    DISTANCE       INT DEFAULT 0 NOT NULL,
    LINE_ID        BIGINT        NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BEFORE_STATION) REFERENCES STATION (ID),
    FOREIGN KEY (NEXT_STATION) REFERENCES STATION (ID),
    FOREIGN KEY (LINE_ID) REFERENCES LINE (ID)
);

INSERT INTO LINE (name)
VALUES ('2호선');

INSERT INTO STATION (name)
VALUES ('잠실');
INSERT INTO STATION (name)
VALUES ('강남');
INSERT INTO STATION (name)
VALUES ('선릉');
INSERT INTO STATION (name)
VALUES ('삼성');
