INSERT INTO LINE (name)
VALUES ('2호선');
INSERT INTO LINE (name)
VALUES ('3호선');
INSERT INTO LINE (name)
VALUES ('4호선');

INSERT INTO STATION (name)
VALUES ('잠실');
INSERT INTO STATION (name)
VALUES ('강남');
INSERT INTO STATION (name)
VALUES ('선릉');
INSERT INTO STATION (name)
VALUES ('삼성');

INSERT INTO SECTION (BEFORE_STATION, NEXT_STATION, DISTANCE, LINE_ID)
VALUES (2, 3, 5, 2);

INSERT INTO SECTION (BEFORE_STATION, NEXT_STATION, DISTANCE, LINE_ID)
VALUES (3, 4, 5, 2);

INSERT INTO SECTION (BEFORE_STATION, NEXT_STATION, DISTANCE, LINE_ID)
VALUES (1, 2, 1, 1);
