DELETE
FROM SECTION;
DELETE
FROM LINE;
DELETE
FROM STATION;

INSERT INTO LINE (id, name)
VALUES (1, '2호선');
INSERT INTO LINE (id, name)
VALUES (2, '3호선');
INSERT INTO LINE (id, name)
VALUES (3, '4호선');

INSERT INTO STATION (id, name)
VALUES (1, '잠실');
INSERT INTO STATION (id, name)
VALUES (2, '강남');
INSERT INTO STATION (id, name)
VALUES (3, '선릉');
INSERT INTO STATION (id, name)
VALUES (4, '삼성');

insert into SECTION (BEFORE_STATION, NEXT_STATION, DISTANCE, LINE_ID)
VALUES (2, 3, 5, 2);

insert into SECTION (BEFORE_STATION, NEXT_STATION, DISTANCE, LINE_ID)
VALUES (3, 4, 5, 2);

insert into SECTION (BEFORE_STATION, NEXT_STATION, DISTANCE, LINE_ID)
VALUES (1, 2, 1, 1);
