CREATE TABLE IF NOT EXISTS STATION
(
    id BIGINT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(id)
    );

CREATE TABLE IF NOT EXISTS LINE
(
    id BIGINT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    color VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
    );

CREATE TABLE IF NOT EXISTS sections
(
    id BIGINT AUTO_INCREMENT NOT NULL,
    line_id BIGINT NOT NULL,
    departure_id BIGINT NOT NULL,
    arrival_id BIGINT NOT NULL,
    distance INT NOT NULL,
    PRIMARY KEY(id)
    );
