DROP TABLE IF EXISTS SECTION;
DROP TABLE IF EXISTS STATION;
DROP TABLE IF EXISTS LINE;

CREATE TABLE IF NOT EXISTS STATION
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY(id)
    );

CREATE TABLE IF NOT EXISTS LINE
(
    id BIGINT UNSIGNED NOT NULL auto_increment,
    name VARCHAR(255) NOT NULL UNIQUE,
    color VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
    );

CREATE TABLE IF NOT EXISTS SECTION
(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    distance BIGINT UNSIGNED NOT NULL,
    upstation_id BIGINT UNSIGNED NOT NULL,
    downstation_id BIGINT UNSIGNED NOT NULL,
    line_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (upstation_id) REFERENCES STATION(id) ON DELETE CASCADE,
    FOREIGN KEY (downstation_id) REFERENCES STATION(id) ON DELETE CASCADE,
    FOREIGN KEY (line_id) REFERENCES LINE(id) ON DELETE CASCADE
    );